import { prisma } from '@/lib/prisma';
import { updateProjectProgressReport } from '@/app/actions/updateProjectProgressReport';
import { deleteProjectProgressReport } from '@/app/actions/deleteProjectProgressReport';
import { requireProjectProgressReportAccess } from '@/lib/auth';

export default async function EditProgressReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const reportId = Number(id);
  await requireProjectProgressReportAccess(reportId);
  const report = await prisma.projectProgressReport.findUnique({ where: { id: reportId }, include: { project: { select: { title: true, program: { select: { name: true } } } }, submittedBy: { select: { name: true } } } });
  if (!report) return <h1>Progress report not found</h1>;
  return <div className="mx-auto max-w-3xl rounded-xl border border-gray-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-green-800">{report.project.program.name} · {report.project.title}</p><h1 className="mt-1 text-2xl font-bold">Edit progress report</h1><p className="mt-2 text-sm text-gray-500">Submitted by {report.submittedBy.name} on {report.createdAt.toLocaleDateString('en-UG', { day: 'numeric', month: 'long', year: 'numeric' })}.</p><form action={updateProjectProgressReport} className="mt-6 grid gap-4"><input type="hidden" name="id" value={report.id} /><label className="grid gap-1 text-sm font-medium">Reporting period<input name="reportingPeriod" defaultValue={report.reportingPeriod} required className="rounded border border-gray-300 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Implementation summary<textarea name="summary" defaultValue={report.summary} rows={5} required className="rounded border border-gray-300 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Key achievements<textarea name="achievements" defaultValue={report.achievements} rows={5} required className="rounded border border-gray-300 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Challenges and risks<textarea name="challenges" defaultValue={report.challenges} rows={5} required className="rounded border border-gray-300 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Next steps<textarea name="nextSteps" defaultValue={report.nextSteps} rows={5} required className="rounded border border-gray-300 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Evidence link <span className="font-normal text-gray-500">(optional)</span><input name="evidenceUrl" type="url" defaultValue={report.evidenceUrl ?? ''} className="rounded border border-gray-300 px-3 py-2 font-normal" /></label><button type="submit" className="w-fit rounded bg-green-800 px-4 py-2 text-sm font-semibold text-white hover:bg-green-900">Save changes</button></form><form action={deleteProjectProgressReport} className="mt-6"><input type="hidden" name="id" value={report.id} /><button type="submit" className="text-sm font-semibold text-red-700 hover:underline">Delete progress report</button></form></div>;
}
