import { prisma } from '@/lib/prisma';
import { createDocument } from '@/app/actions/operations';
import { isProgramManager, requireStaff } from '@/lib/auth';

export default async function DocumentsPage() {
  const user = await requireStaff(); const projectWhere = isProgramManager(user) ? { program: { managerId: user.id } } : {};
  const [projects, documents] = await Promise.all([prisma.project.findMany({ where: projectWhere, select: { id: true, title: true } }), prisma.document.findMany({ where: isProgramManager(user) ? { project: projectWhere } : {}, include: { project: { select: { title: true } } }, orderBy: { createdAt: 'desc' } })]);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Document library</h1><p className="mt-1 text-sm text-gray-500">Strategic plans, policies, reports and evidence. Public files still require approval.</p></div><form action={createDocument} encType="multipart/form-data" className="grid gap-3 rounded-xl border border-green-100 bg-white p-5 md:grid-cols-3"><input name="title" required placeholder="Document title" className="rounded border p-2"/><input name="file" type="file" className="rounded border p-2"/><input name="fileUrl" type="url" placeholder="Or external file URL" className="rounded border p-2"/><select name="category" required className="rounded border p-2"><option value="">Category</option><option>Strategic plan</option><option>Policy</option><option>Project evidence</option><option>Research</option><option>Board report</option></select><select name="visibility" className="rounded border p-2"><option value="internal">Internal</option><option value="public">Public after approval</option></select><select name="projectId" className="rounded border p-2"><option value="">Organisation-wide</option>{projects.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select><textarea name="description" placeholder="Description (optional)" className="rounded border p-2"/><button className="rounded bg-green-800 px-4 py-2 text-sm font-semibold text-white">Submit document</button></form><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead><tr className="bg-gray-50 text-left text-xs uppercase text-gray-500"><th className="p-3">Document</th><th>Category</th><th>Project</th><th>State</th></tr></thead><tbody>{documents.map(d => <tr key={d.id} className="border-t"><td className="p-3"><a href={d.fileUrl} className="font-semibold text-green-800 hover:underline">{d.title}</a></td><td>{d.category}</td><td>{d.project?.title ?? 'Organisation-wide'}</td><td className="capitalize">{d.status} · {d.visibility}</td></tr>)}</tbody></table>{!documents.length && <p className="p-6 text-center text-sm text-gray-500">No documents yet.</p>}</div></div>;
}
