import { prisma } from '@/lib/prisma';
import { createDeliveryRecord } from '@/app/actions/operations';
import { isProgramManager, requireStaff } from '@/lib/auth';

export default async function DeliveryPage() {
  const user = await requireStaff(); const where = isProgramManager(user) ? { program: { managerId: user.id } } : {};
  const [projects, records] = await Promise.all([prisma.project.findMany({ where, select: { id: true, title: true, program: { select: { name: true } } }, orderBy: { title: 'asc' } }), prisma.deliveryRecord.findMany({ where: { project: where }, include: { project: { select: { title: true } } }, orderBy: { activityDate: 'desc' } })]);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Delivery & impact records</h1><p className="mt-1 text-sm text-gray-500">Submitted records require admin approval before contributing to live impact totals.</p></div><form action={createDeliveryRecord} className="grid gap-3 rounded-xl border border-green-100 bg-white p-5 md:grid-cols-3"><select name="projectId" required className="rounded border p-2"><option value="">Project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.program.name} — {p.title}</option>)}</select><select name="metricType" required className="rounded border p-2"><option value="">Impact type</option><option value="pads_distributed">Pads distributed</option><option value="trees_planted">Trees planted</option><option value="schools_reached">Schools reached</option><option value="volunteer_hours">Volunteer hours</option><option value="other">Other delivery</option></select><input name="quantity" type="number" min="0" required placeholder="Quantity" className="rounded border p-2"/><input name="activityDate" type="date" required className="rounded border p-2"/><input name="evidenceUrl" type="url" placeholder="Evidence link (optional)" className="rounded border p-2"/><input name="notes" placeholder="Notes (optional)" className="rounded border p-2"/><button className="rounded bg-green-800 px-4 py-2 text-sm font-semibold text-white">Submit for review</button></form><div className="space-y-2">{records.map(r => <article key={r.id} className="flex items-center justify-between rounded-lg border bg-white p-4 text-sm"><div><b>{r.metricType.replaceAll('_', ' ')}</b><p className="text-gray-500">{r.project.title} · {r.activityDate.toLocaleDateString('en-UG')}</p></div><div className="text-right"><b>{r.quantity.toLocaleString()}</b><p className="capitalize text-xs text-gray-500">{r.status}</p></div></article>)}{!records.length && <p className="rounded border border-dashed p-6 text-center text-sm text-gray-500">No delivery records yet.</p>}</div></div>;
}
