import { prisma } from '@/lib/prisma';
import { createBeneficiarySession } from '@/app/actions/operations';
import { isProgramManager, requireStaff } from '@/lib/auth';

export default async function BeneficiariesPage() {
  const user = await requireStaff(); const where = isProgramManager(user) ? { program: { managerId: user.id } } : {};
  const [projects, sessions] = await Promise.all([prisma.project.findMany({ where, select: { id: true, title: true, program: { select: { name: true } } }, orderBy: { title: 'asc' } }), prisma.beneficiarySession.findMany({ where: { project: where }, include: { project: { select: { title: true } } }, orderBy: { sessionDate: 'desc' } })]);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Beneficiary tracking</h1><p className="mt-1 text-sm text-gray-500">Record aggregate outreach only; do not enter names or other sensitive personal data.</p></div><form action={createBeneficiarySession} className="grid gap-3 rounded-xl border border-green-100 bg-white p-5 md:grid-cols-3"><select name="projectId" required className="rounded border p-2"><option value="">Project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.program.name} — {p.title}</option>)}</select><input name="organisation" required placeholder="School / community" className="rounded border p-2"/><input name="location" required placeholder="Location" className="rounded border p-2"/><input name="sessionType" required placeholder="Session type" className="rounded border p-2"/><input name="beneficiaryCount" type="number" min="0" required placeholder="People reached" className="rounded border p-2"/><input name="sessionDate" type="date" required className="rounded border p-2"/><textarea name="notes" placeholder="Notes (optional)" className="rounded border p-2 md:col-span-2"/><button className="rounded bg-green-800 px-4 py-2 text-sm font-semibold text-white">Record session</button></form><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead><tr className="bg-gray-50 text-left text-xs uppercase text-gray-500"><th className="p-3">Date</th><th>School / community</th><th>Project</th><th>Reached</th></tr></thead><tbody>{sessions.map(s => <tr key={s.id} className="border-t"><td className="p-3">{s.sessionDate.toLocaleDateString('en-UG')}</td><td>{s.organisation}<span className="block text-xs text-gray-500">{s.location} · {s.sessionType}</span></td><td>{s.project.title}</td><td className="font-semibold">{s.beneficiaryCount.toLocaleString()}</td></tr>)}</tbody></table>{!sessions.length && <p className="p-6 text-center text-sm text-gray-500">No outreach sessions recorded.</p>}</div></div>;
}
