import { prisma } from '@/lib/prisma';
import Link from 'next/link';
import { isProgramManager, requireStaff } from '@/lib/auth';

export default async function ImplementationDashboardPage() {
  const user = await requireStaff(); const where = isProgramManager(user) ? { program: { managerId: user.id } } : {};
  const projects = await prisma.project.findMany({ where, select: { id: true, title: true, location: true, latitude: true, longitude: true, program: { select: { name: true } } }, orderBy: { title: 'asc' } });
  return <div className="space-y-7"><div><p className="text-sm font-semibold text-green-800">Implementation overview</p><h1 className="mt-1 text-2xl font-bold">Impact dashboard</h1><p className="mt-2 text-sm text-gray-500">Project coverage for {isProgramManager(user) ? 'your programme' : 'all programmes'}.</p></div><section className="rounded-xl border bg-white"><div className="border-b px-5 py-4"><h2 className="font-bold">Project coverage</h2><p className="text-sm text-gray-500">Open a saved location, or add coordinates to put a project on the public map.</p></div><div className="divide-y">{projects.map((project) => <div key={project.id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="font-semibold">{project.title}</p><p className="text-sm text-gray-500">{project.program.name} · {project.location}</p></div>{project.latitude !== null && project.longitude !== null ? <a href={`https://www.openstreetmap.org/?mlat=${project.latitude}&mlon=${project.longitude}#map=12/${project.latitude}/${project.longitude}`} target="_blank" rel="noreferrer" className="text-sm font-semibold text-green-800 underline">Open location</a> : <Link href={`/admin/projects/${project.id}/edit`} className="text-sm font-semibold text-green-800 underline">Add coordinates</Link>}</div>)}{!projects.length && <p className="p-6 text-sm text-gray-500">No projects in scope.</p>}</div></section></div>;
}
