import { prisma } from '@/lib/prisma';
import { reviewDeliveryRecord, reviewDocument, reviewImpactMetric, reviewProgressReport, reviewReport, reviewStory } from '@/app/actions/operations';
import { requireAdmin } from '@/lib/auth';

function Review({ id, action }: { id: number; action: (formData: FormData) => Promise<void> }) { return <form action={action} className="flex gap-2"><input type="hidden" name="id" value={id}/><button name="status" value="approved" className="rounded bg-green-800 px-3 py-1 text-xs font-semibold text-white">Approve</button><button name="status" value="rejected" className="rounded bg-red-700 px-3 py-1 text-xs font-semibold text-white">Reject</button></form>; }

export default async function ApprovalsPage() {
  await requireAdmin();
  const [delivery, documents, reports, stories, libraryReports, metrics] = await Promise.all([prisma.deliveryRecord.findMany({ where: { status: 'submitted' }, include: { project: { select: { title: true } } }, orderBy: { createdAt: 'asc' } }), prisma.document.findMany({ where: { status: 'submitted' }, include: { project: { select: { title: true } } }, orderBy: { createdAt: 'asc' } }), prisma.projectProgressReport.findMany({ where: { status: 'submitted' }, include: { project: { select: { title: true } } }, orderBy: { createdAt: 'asc' } }), prisma.story.findMany({ where: { status: 'submitted' }, orderBy: { createdAt: 'asc' } }), prisma.report.findMany({ where: { status: 'submitted' }, orderBy: { createdAt: 'asc' } }), prisma.impactMetric.findMany({ where: { status: 'draft' }, orderBy: { createdAt: 'asc' } })]);
  const rows = [...delivery.map(x => ({ key: `d${x.id}`, label: `${x.metricType.replaceAll('_', ' ')} — ${x.quantity.toLocaleString()}`, context: x.project.title, id: x.id, action: reviewDeliveryRecord })), ...documents.map(x => ({ key: `doc${x.id}`, label: x.title, context: `${x.category} · ${x.project?.title ?? 'Organisation-wide'}`, id: x.id, action: reviewDocument })), ...reports.map(x => ({ key: `r${x.id}`, label: x.reportingPeriod, context: `Progress report · ${x.project.title}`, id: x.id, action: reviewProgressReport })), ...stories.map(x => ({ key: `s${x.id}`, label: x.headline, context: 'Story awaiting publication', id: x.id, action: reviewStory })), ...libraryReports.map(x => ({ key: `lr${x.id}`, label: x.title, context: 'Library report awaiting publication', id: x.id, action: reviewReport })), ...metrics.map(x => ({ key: `m${x.id}`, label: x.title, context: 'Impact metric awaiting publication', id: x.id, action: reviewImpactMetric }))];
  return <div><h1 className="text-2xl font-bold">Approval workflow</h1><p className="mt-1 text-sm text-gray-500">Review submitted delivery figures, documents and management reports before they are approved.</p><div className="mt-6 space-y-3">{rows.map(row => <article key={row.key} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-white p-4"><div><p className="font-semibold capitalize">{row.label}</p><p className="text-sm text-gray-500">{row.context}</p></div><Review id={row.id} action={row.action}/></article>)}{!rows.length && <p className="rounded-lg border border-dashed p-8 text-center text-sm text-gray-500">Nothing awaiting approval.</p>}</div></div>;
}
