import { prisma } from '@/lib/prisma';
import { createReminder, updateReminderStatus } from '@/app/actions/operations';
import { isProgramManager, requireStaff } from '@/lib/auth';

export default async function RemindersPage() {
  const user = await requireStaff(); const projectWhere = isProgramManager(user) ? { program: { managerId: user.id } } : {};
  const today = new Date();
  const [projects, reminders, overdueMilestones, dueFunding, applicants] = await Promise.all([prisma.project.findMany({ where: projectWhere, select: { id: true, title: true } }), prisma.reminder.findMany({ where: isProgramManager(user) ? { project: projectWhere } : {}, include: { project: { select: { title: true } } }, orderBy: { dueDate: 'asc' } }), prisma.milestone.findMany({ where: { project: projectWhere, endDate: { lt: today } }, include: { project: { select: { title: true } } } }), isProgramManager(user) ? Promise.resolve([]) : prisma.fundingCommitment.findMany({ where: { status: { notIn: ['declined', 'completed'] }, OR: [{ deadline: { lte: new Date(today.getTime() + 30 * 86400000) } }, { reportDueDate: { lte: new Date(today.getTime() + 30 * 86400000) } }] }, include: { partner: { select: { organizationName: true } } } }), isProgramManager(user) ? Promise.resolve(0) : prisma.volunteer.count({ where: { status: 'applicant' } })]);
  const alerts = [...overdueMilestones.map(item => `Overdue milestone: ${item.title} (${item.project.title})`), ...dueFunding.map(item => `Grant action due: ${item.title} (${item.partner.organizationName})`), ...(applicants ? [`${applicants} new volunteer application${applicants === 1 ? '' : 's'}`] : [])];
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Alerts & reminders</h1><p className="mt-1 text-sm text-gray-500">Automatic deadline and application alerts plus manual follow-ups.</p></div>{alerts.length > 0 && <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">Needs attention</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-900">{alerts.map(alert => <li key={alert}>{alert}</li>)}</ul></section>}<form action={createReminder} className="grid gap-3 rounded-xl border border-green-100 bg-white p-5 md:grid-cols-3"><input name="title" required placeholder="Reminder title" className="rounded border p-2"/><select name="type" required className="rounded border p-2"><option value="">Type</option><option>Grant deadline</option><option>Report due</option><option>Milestone</option><option>Follow-up</option></select><input name="dueDate" type="date" required className="rounded border p-2"/><select name="projectId" className="rounded border p-2"><option value="">Organisation-wide</option>{projects.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select><input name="notes" placeholder="Notes (optional)" className="rounded border p-2"/><button className="rounded bg-green-800 px-4 py-2 text-sm font-semibold text-white">Add reminder</button></form><div className="space-y-2">{reminders.map(r => <article key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-white p-4"><div><b>{r.title}</b><p className="text-sm text-gray-500">{r.type} · {r.project?.title ?? 'Organisation-wide'} · due {r.dueDate.toLocaleDateString('en-UG')}</p></div><form action={updateReminderStatus} className="flex gap-2"><input type="hidden" name="id" value={r.id}/><select name="status" defaultValue={r.status} className="rounded border p-1 text-sm"><option value="open">Open</option><option value="done">Done</option><option value="dismissed">Dismissed</option></select><button className="rounded bg-gray-100 px-3 text-sm">Save</button></form></article>)}{!reminders.length && <p className="rounded border border-dashed p-6 text-center text-sm text-gray-500">No reminders yet.</p>}</div></div>;
}
